# Artifact Hub repository metadata file
#
# ref: https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml

repositoryID: alertmanager-webhook-adapter
owners:
  - name: kimicao1010
    email: kimicao1010@126.com
ignore: []
